### ISSUE TITLE
Cannot import name '_cystdf' from partially initialized module 'deps.cystdf'

### ISSUE THREAD

**Issue by Prehistoricman** [noonchen/STDF-Viewer#49] opened 2021-08-25 18:42 UTC
PS D:\Downloads\STDF-Viewer-main> python '.\STDF Viewer.py'
Traceback (most recent call last):
  File "D:\Downloads\STDF-Viewer-main\STDF Viewer.py", line 38, in <module>
    from deps.cystdf import stdfParser, setByteSwap
  File "D:\Downloads\STDF-Viewer-main\deps\cystdf\__init__.py", line 27, in <module>
    from . import _cystdf
ImportError: cannot import name '_cystdf' from partially initialized module 'deps.cystdf' (most likely due to a circular import) (D:\Downloads\STDF-Viewer-main\deps\cystdf\__init__.py)

Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32

Windows 10 19042.1165

I also tried python 3.8 and got the same error after addressing all the 3.9 specific code.

**Comment by noonchen** [comment] 2021-08-28 00:04
> I see. I found that previously, this viewer was pure python and this old version works on Windows without cystdf.
> 
Yes, the old version uses `pystdf` to parse the stdfs, but its performance is really an obstacle for large files, that's why I wrote a cython module `cystdf`.

> I also see a Windows binary is part of the releases. It's an installer (why?).
> 
The installer can help me associate .std(f) with STDF-Viewer, so the users can double click files to open the files.

> 
> In general there are no requirements or setup notes in this repo. I figure out that numpy, toml, etc. are required because they cause errors. Same for building this Cython module.
> 
Sorry, that's my bad. I thought nobody cares about the code and just wants the executable, I'll add a requirement list some days later.

> 
> Now getting somewhat off-topic, I tried building cystdf in WSL (Ubuntu) but get many compilation errors. They all say something like "x not allowed without gil". Do you know what that could be?
> 
That's interesting, I have a ubuntu build task in my github workflow and never see any compilation error. "X not allowed without gil" is usually due to cython cannot find C definitions, then treats C structs or functions as python object, Would you post the detailed output here (or in a file)? The root cause generally places at the top.

**Comment by Prehistoricman** [comment] 2021-08-28 19:13
Cython says its version is 0.29.24. I just installed it with pip.

This is the start of the errors:
```
Compiling cystdf_amalgamation.pyx because it changed.
[1/1] Cythonizing cystdf_amalgamation.pyx

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as cnp
cimport cython
from cython.view cimport array as cyarray
from cython.parallel import prange

from includes.pthread cimport *
^
------------------------------------------------------------

cystdf_amalgamation.pyx:39:0: 'includes/pthread.pxd' not found
```
Same error shows up for several other imports. Some Googling shows this is because there are no __init__.py files for these modules.

I added __init__.py for all the imports. Now I get this compilation error:
```
running build_ext
building '_cystdf' extension
creating build
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/stdf4_src
creating build/temp.linux-x86_64-3.9/stdf4_src/bzip2_src
creating build/temp.linux-x86_64-3.9/stdf4_src/zlib_src
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_LARGEFILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I./hashmap_src -I./sqlite3_src -I./stdf4_src -I/home/zeke/.local/lib/python3.9/site-packages/numpy/core/include -I/usr/include/python3.9 -c cystdf_amalgamation.c -o build/temp.linux-x86_64-3.9/cystdf_amalgamation.o -fopenmp
cystdf_amalgamation.c:80:10: fatal error: Python.h: No such file or directory
   80 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

**Comment by noonchen** [comment] 2021-08-29 01:03
> Cython says its version is 0.29.24. I just installed it with pip.
> 
It reminds me￼ a same issue I've seen in github build tasks, I resolved it by installed cython 3.0a6:

```
Pip install cython==3.0a6
```
This should be working.

**Comment by Prehistoricman** [comment] 2021-08-29 12:37
Cython 3.0a6 is still giving me the same Python.h error. The only difference I see is that the `__init__.py` files are no longer needed

**Comment by noonchen** [comment] 2021-08-29 14:57
> Cython 3.0a6 is still giving me the same Python.h error. The only difference I see is that the `__init__.py` files are no longer needed

The error is quite self-explained, seems like your ubuntu doesn't have pyhthon-dev which includes header files for python.

Try:
```
sudo apt-get install python3.9-dev
```

**Comment by noonchen** [comment] 2021-09-02 09:13
Hi @Prehistoricman , is this issue resolved? 

I'll close this issue now, If you have any questions, please reopen this issue or open a new one.

**Closed by noonchen** 2021-09-02 09:13 UTC
Labels: not a bug
