### ISSUE TITLE
Some stdf file can't work at STDF-Viewer-3.1.0 but it could be working at STDF-Viewer-2.0

### ISSUE THREAD

**Issue by ChenJavery** [noonchen/STDF-Viewer#64] opened 2021-12-08 06:32 UTC
Some stdf files can't work at STDF-Viewer-3.1.0 but it could be working at STDF-Viewer-2.0
Did you have any idea that why Ver2.0 could work but not work at ver3.1.0, and any suggestions for this issue? Thx.
***********************************************
Error msg snapshot as below:
![error1](https://user-images.githubusercontent.com/95664588/145156348-c2d8794a-6a6a-47ce-819b-445936eb28e4.JPG)
![error2](https://user-images.githubusercontent.com/95664588/145156448-3c8e1a3f-d9f9-4f69-a9ae-f98ce65e0ac8.JPG)
***********************************************
Error log as attached file:
[STDF-Viewer.log](https://github.com/noonchen/STDF-Viewer/files/7673711/STDF-Viewer.log)
***********************************************
snapshot of  db file as below:
![DB](https://user-images.githubusercontent.com/95664588/145158123-6aa75f10-1ae9-4934-b790-b76fb9823467.JPG)
***********************************************

It seems that stdf file has null at HBIN/SBIN the version3.1.0 will report the error msg

**Comment by noonchen** [comment] 2021-12-08 08:19
@ChenJavery 
The error is caused by the NULL value in `Flag` column.

In the STDF standards, data of each DUT is enclosed in a PIR/PRR pair. Every PIR in STDF will write `HEAD_NUM`, `SITE_NUM` and `DutIndex` into `Dut_Info` table, and the corresponding PRR will complete `TestCount`, `HBIN` and `Flag` columns at least (these fields are not omittable), that means a valid STDF shouldn't have a `NULL` in Flag column, otherwise the corresponding PRR is missing from the file.

If you believe the file is OK, you can compress the file using `gz` or `bzip` and send it to me, I'll help you investigate the datalog.

**Comment by noonchen** [comment] 2021-12-10 16:06
@ChenJavery  Can you try the code in the dev branch I just pushed? The crash should be fixed.

**Comment by noonchen** [comment] 2021-12-16 06:01
@ChenJavery Can you try the new V3.2.0 release to see if those files can be loaded?

**Comment by ChenJavery** [comment] 2021-12-20 01:56
Hi noonchen,

I meet a new issue when I select the "Bin Summary", pls see the error msg as below snapshot & log file:
--------------------------------------------------------------------
![error](https://user-images.githubusercontent.com/95664588/146700718-bcdf34bb-236b-42ba-999a-01395a4a7c89.JPG)
--------------------------------------------------------------------
[STDF-Viewer-2021-12-20.log](https://github.com/noonchen/STDF-Viewer/files/7742124/STDF-Viewer-2021-12-20.log)
--------------------------------------------------------------------

**Comment by noonchen** [comment] 2021-12-20 04:43
Hi, @ChenJavery 

Thanks for the feedback and the log, apparently there are some places that I've missed, I'll release another patch to fix this issue when I finished my current work.

**Comment by noonchen** [comment] 2021-12-20 13:09
I manually removed some PRR from a stdf file, based on my test, the latest pull request should fix this issue, you can try it out after it's merged.

**Comment by noonchen** [comment] 2021-12-24 13:04
The v3.3.0 is released, let me know if it's working for you ;)

**Comment by noonchen** [comment] 2021-12-27 05:19
Assuming this issue is resolved in the latest version, I'm closing.

If the issue persists, plz reopen it.

**Closed by noonchen** 2021-12-27 05:19 UTC
Labels: improvement
